---
# tasks file for clickhouse-role
- name: Install clickhouse distrib
  become: true
  ansible.builtin.yum:
    name: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
    disable_gpg_check: true
  with_items: "{{ clickhouse_packages }}"
  notify: Start clickhouse service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 82
  changed_when: create_db.rc == 0